### ISSUE TITLE
Full Speed

### ISSUE THREAD

**Issue by nightwing878** [Retrobyte/Retrobyte#1]
Not really an Issue, just didn't know how to contact you via anything else.

I like what you did here, I made a bot not too long ago that bypasses the captcha as you have stated can be done. Just looking to do a speed comparison between our bots and make mine better.

What code modifications would need to be done in order to bring the bot to full speed. Been messing around with it for a bit but couldn't figure it out.

**Comment by Retrobyte** [comment]
Sorry for the late reply, it has been quite busy the past few months. Now back on topic, bypassing the captcha is essential for you to reach a very fast speed. All delays will also have to be removed as well. For those who are curious, if you wish to bypass the captcha, all that's really required is to strip away about half the links in the code. In particular, it's all the AJAX requests that are required to be executed but again, it's a huge flag that you are using a bot. The reason why this bypasses the captcha is because strangely, the captcha is generated on the non-AJAX request. Also, I'm 99% sure they count your captchas so if you happen to have none on your account and you've reached a fairly decent level, it becomes quite obvious you are cheating. Good luck to all who attempts to do this! Should I remind you that you will almost certainly be banned.
